language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libgeos-dev
    - python-numpy
script:
- python setup.py test
deploy:
  provider: pypi
  user: devseed
  password:
    secure: GH1pYO11lqxM3uuo/n1ll5d6oHEXZI7Ok3YwSfd3WFVeBZj1WWxfnAqBYUjzcoyQJeWbkVXhw1UIYjqkqxsqRXIVll6rgDlDFSZa8rRC4xJfK9Dv1XZxK79OAQM4IDV+NQe+l/xLzwM6cxjhPxYXsO8UMxefPvroqglObQEFXl+JisaPVYjL8qv0i63MU0w+TqpVuhtbqzl17Y1sYRCyPcntBN2pWUQdTdTPwnmHC/W+9nzBIO0t4LeZ8tvCC5OziU3kl9VFaNsUpTAiu6qDIJFgyKIN1NOTssSwmnfOuF70sXxr45SF0os1BwdKMAaE36CNCGMpmsAW9HknsvOAdgRfWM1EhKxBfBXj90hJ0rY91Rp4sCH6xn7zlspsT5xk7OrpPL9jZtbnC6oPgffVyBLu8q3xpYdzZwMyjIA00Zt9om3OPRlfCDUF3D7iodFwHLqn1qccF0CG1T7K4VsqMSosOoUpTT+LkSr/QciY2wh8J2MinWSZ+WtGWqGyJibEG29V8Qm5vklDcYswRiLp5t243UxVgI/L446gM5cew3cbrPPYSkJmbdSCTtkhJp/HtSG2SKczswW4A4/Ut4jQ+6rjSYarZHU6YNJxYcovMefIAwHmSMBWO3F7Uyrt59XIkrRCGiTRZkpBz5AP8N9dmK+WAxfHV++TH9NOyKEAWWk=
  on:
    distributions: sdist bdist_wheel
    repo: developmentseed/sentinel-s3
    branch: master
